### ISSUE TITLE
.Net bin parsing issue

### ISSUE THREAD

**Issue by theflakes** [frank2/exe-rs#4]
Thank you for this crate. I've been using the Goblin crate, but it lacks some features yours has, such as getting the original filename.

This is the Rust program I'm working on: https://github.com/theflakes/fmd
It's a PE cmd line forensic tool.
In the "main.rs" file is the "get_pe_file_info" fn that I'm using your crate in to parse the structure that contains the original filename and other fields.

I think there is an issue with .Net binary parsing of the vs_version. When I run this against a .Net binary that shows an original filename in the file properties windows from Windows Explorer I get an error:

`thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: CorruptDataDirectory', src\main.rs:324:39`

Thanks again for the crate!

**Comment by frank2** [comment]
Really happy you found it useful! Means a lot!

Yeah the versioning setup in the resource directory is a pain in the ass. There's a bug in CFF Explorer with parsing VS_VERSION and a bunch of other stuff. The code is ugly so I'm not surprised there's an issue.

Is the .NET binary malware? Do you have a hash I can search to run it against exe-rs and see what the bug is? If it's not malware, do you have somewhere I can download it to run against the crate? I've been working on a bunch of C++ lately and I'd love to get back to this project if people are working on it!

Thanks again for reporting this!

**Comment by theflakes** [comment]
Nice and thanks!

The one binary I can share with you is found here: https://github.com/BloodHoundAD/SharpHound/releases/tag/v1.1.0

It's the zip file and is the SharpHound.exe .Net binary.

Thanks again

**Comment by frank2** [comment]
Figured out the problem. exe-rs is expecting there to be a VSStringFileInfo structure immediately after a VSFixedFileInfo structure. In the executable you linked me, VSVarFileInfo comes *before* VSStringFileInfo, which is either nonstandard or is documented and I just missed it in the godawful documentation that exists for this format.

It should be an easy fix-- detect which structure is actually there in the file first instead of assuming. I'll have a fix soon. Thanks for reporting this-- the parsing of these structures is undoubtedly riddled with bugs like this.

**Comment by theflakes** [comment]
Nice work! I've started digging into the work you're doing on this. Not easy going through all the docs for sure so thanks again.

**Comment by frank2** [comment]
This is now fixed as of https://github.com/frank2/exe-rs/commit/4c76891552f2b884dbab32719292944c8fe3cfe3! The official release with this fix will be 0.5.5. Thanks again for reporting!

**Comment by frank2** [comment]
This is live in 0.5.6 (not 0.5.5, that was a mistake).
